module problems.problem2;
import std.stdio;

void problem2() 
{
	writeln( "Each new term in the Fibonacci sequence is generated by adding the previous two terms. " );
	writeln( "By starting with 1 and 2, the first 10 terms will be:" );
	writeln( "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ..." );
	writeln( "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms." );

	int[] fibs;
	fibs.length = 10;
	fibs[ 0 ] = 1;
	fibs[ 1 ] = 2;
	const int max_fib = cast(int) 4e6; 
	for ( int i = 2; i < fibs.length; i++ ) 
	{
		if ( i + 1 >= fibs.length )
		{
			writefln( "resizing from: %d, to: %d", fibs.length, fibs.length * 2 ); 
			fibs.length *= 2;
		}
		
		fibs[ i ] = fibs[ i - 1 ] + fibs[ i - 2 ];
		
		if ( fibs[ i ] > max_fib ) 
		{ 
			break;
		}
		
		writefln( "fibs[%d]: %d ", i, fibs[ i ] );
	}
	
	int sum = 0;
	foreach ( num ; fibs )
	{
		sum += num * ( num % 2 == 0 );
	}
	
	writefln( "sum: %d", sum );
}
